services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=me@canverse.dev"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "9090:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  server:
    container_name: finance-be
    build:
      context: ./finance-api
      dockerfile: Dockerfile
    secrets:
      - db-password
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finance
      - SPRING_DATASOURCE_PASSWORD=234234
      - SPRING_DATASOURCE_USERNAME=postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"
      - "traefik.http.routers.server.rule=Host(`api.fin.canverse.dev`)"
    depends_on:
      db:
        condition: service_healthy
  
  client:
    container_name: finance-fe
    build:
      context: ./finance-web
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.routers.web.rule=Host(`fin.canverse.dev`)"
    expose:
      - 80
    environment:
      - API_BASE_URL=https://api.fin.canverse.dev/api/
    depends_on:
      - server
    
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data2:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=finance
      - POSTGRES_PASSWORD=234234
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data2:
  letsencrypt:
secrets:
  db-password:
    file: db/password.txt
