cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
jwt:
  access-token-expiration-in-seconds: 120
  refresh-token-expiration-in-seconds: 3600
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
logging:
  level:
    org:
      hibernate:
        stat: error
        SQL: error
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: when_authorized